### PR TITLE
optimize: fix StyleCheck errors for hippo4j

### LINKED ISSUE #1229: [TASK] About CheckStyle Errors
There are errors related to CheckStyle. I hope someone can fix them and make pull requests.

  - [ ] hippo4j-threadpool-infra-common @yhc777 
  - [x] hippo4j-threadpool-core @dmego 
  - [x] hippo4j-threadpool-adapter-web
  - [x] hippo4j-threadpool-spring-boot-starter-adapter-web
  - [x] hippo4j-threadpool-config-spring-boot-starter
  - [x] spring-plugin-common
  - [x] hippo4j-threadpool-config-spring-boot-1x-starter
  - [x] spring-boot-1.x-plugin
  - [x] spring-boot-2.x-plugin
  - [x] thread-pool-plugin
  - [x] apollo-plugin
  - [x] hippo4j-agent-bootstrap
  - [x] hippo4j-example-core
  - [x] hippo4j-threadpool-config-nacos-example
  - [x] hippo4j-threadpool-config-apollo-example
  - [x] hippo4j-threadpool-config-zookeeper
  - [x] hippo4j-threadpool-config-consul-example
  - [x] hippo4j-threadpool-config-etcd-example
  - [x] hippo4j-threadpool-config-nacos-spring-boot-1x
  - [x] hippo4j-threadpool-config-apollo-spring-boot-1x-example
  - [x] hippo4j-threadpool-server-spring-boot-starter
  - [x] hippo4j-threadpool-adapter-rabbitmq-example
  - [x] hippo4j-threadpool-adapter-stream-rabbitmq-example
  - [x] hippo4j-threadpool-adapter-stream-rocketmq-example
  - [x] hippo4j-threadpool-adapter-rocketmq-example
  - [x] hippo4j-threadpool-adapter-kafka-example
  - [x] hippo4j-threadpool-server-example
  - [x] hippo4j-threadpool-monitor-elasticsearch-example
  - [x] hippo4j-threadpool-rpc
  - [x] hippo4j-threadpool-server-config
  - [ ] hippo4j-agent-core

If everyone wants to fix those errors, they can change <skip.checkstyle.check>true</skip.checkstyle.check> to false and run mvn package to see more details.

Any pull request related to CheckStyle errors can be associated with this issue, and I will update this document when the PR is merged or find new errors.

### PR DESCRIPTION
**Pull request by dmego**
Fixes #1229

Changes proposed in this pull request:

Fix styleCheck errors about module:
- apollo-plugin
- hippo4j-example-core
- hippo4j-threadpool-adapter-kafka-example
- hippo4j-threadpool-adapter-rabbitmq-example
- hippo4j-threadpool-adapter-rocketmq-example
- hippo4j-threadpool-adapter-stream-rocketmq-example
- hippo4j-threadpool-adapter-stream-rabbitmq-example
- hippo4j-threadpool-config-apollo-example
- hippo4j-threadpool-config-apollo-spring-boot-1x-example
- hippo4j-threadpool-config-consul-example
- hippo4j-threadpool-config-etcd-example
- hippo4j-threadpool-config-nacos-example
- hippo4j-threadpool-config-nacos-spring-boot-1x
- hippo4j-threadpool-config-spring-boot-1x-starter
- hippo4j-threadpool-config-spring-boot-starter
- hippo4j-threadpool-config-zookeeper
- hippo4j-threadpool-monitor-elasticsearch-example
- hippo4j-threadpool-server-example
- hippo4j-threadpool-server-config
- spring-boot-1.x-plugin
- spring-boot-2.x-plugin
- thread-pool-plugin
- spring-plugin-common

> Check mailbox configuration when submitting. [Contributor Guide](https://hippo4j.cn/community/contributor-guide)

### CODE REVIEW

File: agents/threadpool/hippo4j-agent-plugin/spring-plugins/spring-plugin-common/src/main/java/cn/hippo4j/agent/plugin/spring/common/conf/SpringBootConfig.java [hunk 1]
```diff
@@ -22,22 +22,37 @@
...
+         * Dynamic
+         */
         public static class Dynamic {
 
+            /**
+             * ThreadPool
+             */
             @SpringBootConfigNode(root = SpringBootConfig.class)
-            public static class Thread_Pool {
+            public static class ThreadPool {
```
Comment (magestacks) [inline agents/threadpool/hippo4j-agent-plugin/spring-plugins/spring-plugin-common/src/main/java/cn/hippo4j/agent/plugin/spring/common/conf/SpringBootConfig.java]: This cannot be changed here, and it will affect the use of functions. should be added to the ignore file.

Comment (magestacks) [reply agents/threadpool/hippo4j-agent-plugin/spring-plugins/spring-plugin-common/src/main/java/cn/hippo4j/agent/plugin/spring/common/conf/SpringBootConfig.java]: Please fix this problem as soon as possible. I am developing the Agent module recently, and I am worried that there will be conflicts in the future, which will make it difficult to merge.

**Review by magestacks — APPROVED** [review]
