### PR TITLE
Fix some module  CheckStyle Errors

### LINKED ISSUE #1229: [TASK] About CheckStyle Errors
There are errors related to CheckStyle. I hope someone can fix them and make pull requests.

  - [ ] hippo4j-threadpool-infra-common @yhc777 
  - [x] hippo4j-threadpool-core @dmego 
  - [x] hippo4j-threadpool-adapter-web
  - [x] hippo4j-threadpool-spring-boot-starter-adapter-web
  - [x] hippo4j-threadpool-config-spring-boot-starter
  - [x] spring-plugin-common
  - [x] hippo4j-threadpool-config-spring-boot-1x-starter
  - [x] spring-boot-1.x-plugin
  - [x] spring-boot-2.x-plugin
  - [x] thread-pool-plugin
  - [x] apollo-plugin
  - [x] hippo4j-agent-bootstrap
  - [x] hippo4j-example-core
  - [x] hippo4j-threadpool-config-nacos-example
  - [x] hippo4j-threadpool-config-apollo-example
  - [x] hippo4j-threadpool-config-zookeeper
  - [x] hippo4j-threadpool-config-consul-example
  - [x] hippo4j-threadpool-config-etcd-example
  - [x] hippo4j-threadpool-config-nacos-spring-boot-1x
  - [x] hippo4j-threadpool-config-apollo-spring-boot-1x-example
  - [x] hippo4j-threadpool-server-spring-boot-starter
  - [x] hippo4j-threadpool-adapter-rabbitmq-example
  - [x] hippo4j-threadpool-adapter-stream-rabbitmq-example
  - [x] hippo4j-threadpool-adapter-stream-rocketmq-example
  - [x] hippo4j-threadpool-adapter-rocketmq-example
  - [x] hippo4j-threadpool-adapter-kafka-example
  - [x] hippo4j-threadpool-server-example
  - [x] hippo4j-threadpool-monitor-elasticsearch-example
  - [x] hippo4j-threadpool-rpc
  - [x] hippo4j-threadpool-server-config
  - [ ] hippo4j-agent-core

If everyone wants to fix those errors, they can change <skip.checkstyle.check>true</skip.checkstyle.check> to false and run mvn package to see more details.

Any pull request related to CheckStyle errors can be associated with this issue, and I will update this document when the PR is merged or find new errors.

### PR DESCRIPTION
**Pull request by DDreame**
#1229 

Changes proposed in this pull request:
- Fix checkType errors about module hippo4j-spring-boot-starter.
- Fix checkType error about module hippo4j-adapter-hystrix.
- Fix checkType error about module hippo4j-adapter-alibaba-dubbo.
- Fix checkType errors about module hippo4j-adapter-dubbo.

### CODE REVIEW

File: hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/core/ClientWorker.java [hunk 1]
```diff
@@ -44,19 +44,7 @@
...
-import static cn.hippo4j.common.constant.Constants.LINE_SEPARATOR;
-import static cn.hippo4j.common.constant.Constants.LISTENER_PATH;
-import static cn.hippo4j.common.constant.Constants.LONG_PULLING_CLIENT_IDENTIFICATION;
-import static cn.hippo4j.common.constant.Constants.LONG_PULLING_TIMEOUT;
-import static cn.hippo4j.common.constant.Constants.LONG_PULLING_TIMEOUT_NO_HANGUP;
-import static cn.hippo4j.common.constant.Constants.NULL;
-import static cn.hippo4j.common.constant.Constants.PROBE_MODIFY_REQUEST;
-import static cn.hippo4j.common.constant.Constants.WEIGHT_CONFIGS;
-import static cn.hippo4j.common.constant.Constants.WORD_SEPARATOR;
+import static cn.hippo4j.common.constant.Constants.*;
```
Comment (magestacks) [inline hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/core/ClientWorker.java]: Import * is not allowed

File: hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/core/ClientWorker.java [hunk 2]
```diff
@@ -147,7 +138,7 @@ public void run() {
                 String itemId = keys[1];
                 String namespace = keys[2];
                 try {
-                    String content = getServerConfig(namespace, itemId, tpId, 3000L);
+                    String content = getServerConfig(namespace, itemId, tpId, HTTP_EXECUTE_TIMEOUT);
```
Comment (magestacks) [inline hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/core/ClientWorker.java]: Why did 3000 become 5000?

Comment (DDreame) [reply hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/core/ClientWorker.java]: because the introduced HTTP timeout setting is a global constant in hippo4j-common, And I have now reverted it to 3000 by creating a constant in the current file.

File: hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/core/ClientWorker.java (hunk 1 above)
Comment (DDreame) [reply hippo4j-spring-boot/hippo4j-spring-boot-starter/src/main/java/cn/hippo4j/springboot/starter/core/ClientWorker.java]: I have fixed the "import *" issue in three files.

**Review by magestacks — APPROVED** [review]
