### PR TITLE
Service exception test

### LINKED ISSUE #1397: Add test case for ServiceException
Code classes that need to develop unit tests:

- `cn.hippo4j.server.common.base.exception.ServiceException`

Please refer to the manual for the first contribution: [guide](https://hippo4j.cn/community/contributor-guide)

Unit test development refers to the following two examples:

- `cn.hippo4j.core.executor.DynamicThreadPoolExecutorTest`
- `cn.hippo4j.core.executor.ExtensibleThreadPoolExecutorTest`

### PR DESCRIPTION
**Pull request by Han-Xinlong**
Fixes #1397

Changes proposed in this pull request:
- Service exception test

> Check mailbox configuration when submitting. [Contributor Guide](https://hippo4j.cn/community/contributor-guide)

### CODE REVIEW

File: threadpool/server/common/src/test/java/cn/hippo4j/server/common/base/ServiceExceptionTest.java [hunk 1]
```diff
@@ -0,0 +1,111 @@
...
+    public void ServiceExceptionTest8(){
+        Throwable cause = new Throwable();
+        ErrorCode errorCode = ErrorCodeEnum.LOGIN_TIMEOUT;
+        String message = ErrorCodeEnum.SERVICE_ERROR.getMessage();
+        ServiceException serviceException = new ServiceException(message, cause, errorCode);
+        Assert.isTrue(Objects.equals(serviceException.getCause().getMessage(), cause.getMessage()));
+        Assert.isTrue(Objects.equals(serviceException.getErrorCode().getCode(), ErrorCodeEnum.LOGIN_TIMEOUT.getCode()));
+        Assert.isTrue(Objects.equals(serviceException.getMessage(), message));
+    }
+
```
Comment (magestacks) [inline threadpool/server/common/src/test/java/cn/hippo4j/server/common/base/ServiceExceptionTest.java]: Delete redundant empty lines

File: threadpool/server/common/src/test/java/cn/hippo4j/server/common/base/ServiceExceptionTest.java [hunk 2]
```diff
@@ -0,0 +1,111 @@
...
+import cn.hippo4j.server.common.base.exception.ServiceException;
+import com.fasterxml.jackson.annotation.JsonTypeInfo;
+import org.checkerframework.checker.units.qual.A;
+import org.junit.jupiter.api.Test;
+
+import java.util.Objects;
+
+/**
+ * Service exception test
+ *
```
Comment (magestacks) [inline threadpool/server/common/src/test/java/cn/hippo4j/server/common/base/ServiceExceptionTest.java]: 删除多余注释空行

**Review by magestacks — APPROVED** [review]
