### PR TITLE
Fix issue 638

### LINKED ISSUE #638: 线程池存在实例不允许删除线程池
判断当前线程池是否存在实例正在运行，如果存在则不允许删除。

### PR DESCRIPTION
**Pull request by shanjianq**
Fixes #638

Changes proposed in this pull request:
- 

> Check mailbox configuration when submitting. [Contributor Guide](https://hippo4j.cn/docs/community/contributor)

### CODE REVIEW

File: hippo4j-console/src/main/java/cn/hippo4j/console/controller/ThreadPoolController.java [hunk 1]
```diff
@@ -84,6 +85,19 @@ public Result saveOrUpdateThreadPoolConfig(@RequestParam(value = "identify", req
...
+        Lease<InstanceInfo> first = CollUtil.getFirst(leases);
+        if (first == null) {
+            threadPoolService.deletePool(reqDTO);
+            return Results.success();
+        }
+        InstanceInfo holder = first.getHolder();
+        String itemTenantKey = holder.getGroupKey();
+        String groupKey = getGroupKey(reqDTO.getTpId(), itemTenantKey);
+        Map<String, CacheItem> content = ConfigCacheService.getContent(groupKey);
+        if (!content.isEmpty()) {
```
Comment (agentart) [inline hippo4j-console/src/main/java/cn/hippo4j/console/controller/ThreadPoolController.java:98]: content 可能会等于空么
