### PR TITLE
[Enhancement] Log printing failure problem in agent mode

### LINKED ISSUE #1428: [Enhancement] Log printing failure problem in agent mode.
## BUG Report
In agent mode, the printing of the log will fail, please check the reason, if it is a bug, please fix it.

The code for reproducing the problem is located at: DynamicThreadPoolRefreshListener class, line 137

### PR DESCRIPTION
**Pull request by Pan-YuJie**
Fixes #1428 

At present, java prints logs mostly with slf4j and log4j/logback, but agent is a separate jar package.

To use slf4j, you need to introduce the package into agent, which may conflict with the business's own slf4j logback log.

And after the agent package uses the slf4j-api package, you need to ensure that the classLoader of the agent is consistent with the classLoader of the business, otherwise conflicts cannot be found or repeated.

### In tomcat

The internal logging for Apache Tomcat uses JULI, a packaged renamed fork of Apache Commons Logging that is hard-coded to use the java.util.logging framework. This ensures that Tomcat's internal logging and any web application logging will remain independent, even if a web application uses Apache Commons Logging.

Reference: https://tomcat.apache.org/tomcat-9.0-doc/logging.html

### In pinpoint and skywalking

Pinoint and skywalking create custom Logger class. They use sender class to transfer trace and metric to collector server.

Reference:
- pinpoint BootLogger  (https://github.com/pinpoint-apm/pinpoint)](https://github.com/pinpoint-apm/pinpoint)
- skywalking ILog  (https://github.com/apache/skywalking)](https://github.com/apache/skywalking)

********

# Solution

There is a Skywalking-like ILOG component in the agent-core package, which removes the ILog component from the existing agent-core package into the infra common package, so that other Agent modules can directly use the custom log component without relying on Slf4j to print the log, avoiding the problem of log non-printing.

Successfully solved：

image-20231112232442138

******

### CODE REVIEW

File: agent/hippo4j-agent-bootstrap/src/main/java/cn/hippo4j/agent/bootstrap/Hippo4jAgent.java [hunk 1]
```diff
@@ -17,22 +17,17 @@
...
 import cn.hippo4j.agent.core.jvm.LoadedLibraryCollector;
-import cn.hippo4j.agent.core.logging.api.ILog;
-import cn.hippo4j.agent.core.logging.api.LogManager;
-import cn.hippo4j.agent.core.plugin.AbstractClassEnhancePluginDefine;
-import cn.hippo4j.agent.core.plugin.EnhanceContext;
-import cn.hippo4j.agent.core.plugin.InstrumentDebuggingClass;
-import cn.hippo4j.agent.core.plugin.PluginBootstrap;
-import cn.hippo4j.agent.core.plugin.PluginException;
-import cn.hippo4j.agent.core.plugin.PluginFinder;
+import cn.hippo4j.agent.core.plugin.*;
```
Comment (magestacks) [inline agent/hippo4j-agent-bootstrap/src/main/java/cn/hippo4j/agent/bootstrap/Hippo4jAgent.java]: Do not import *, please check all submissions.

Comment (Pan-YuJie) [reply agent/hippo4j-agent-bootstrap/src/main/java/cn/hippo4j/agent/bootstrap/Hippo4jAgent.java]: OK，IDAE auto-import package configuration is not set. I will modify it and recommit.

**Review by magestacks — APPROVED** [review]
